default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bootstrapblog_development
  username: ismaelixboy

test:
  <<: *default
  database: bootstrapblog_test
  username: ismaelixboy

production:
  <<: *default
  database: bootstrapblog_production
  username: ismaelixboy
